version: "3"

services:
  nuxt:
    build: ./front/
    container_name: front-app
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm start"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_SITES_PATH}:/etc/nginx/conf.d
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ./ssl/local.nuxt-app.com.tw.crt:/etc/ssl/certs/nginx.crt
      - ./ssl/local.nuxt-app.com.tw.key:/etc/ssl/private/nginx.key
    depends_on:
      - nuxt
